
##server:
  ##port: 8080
##logging:
  ##config: classpath:logback-spring-local.xml
  ##level:
    ##org:
      ##hibernate:
        ##SQL: DEBUG

server:
  port: 8080  # 서버 포트 설정
  servlet:
    context-path: /api  # 모든 API 엔드포인트에 /api 접두사 추가

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb  # MySQL 데이터베이스 URL
    username: user  # 데이터베이스 사용자 이름
    password: pass  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 드라이버

  jpa:
    hibernate:
      ddl-auto: update  # 개발 시에는 'update', 프로덕션에는 'none' 설정
    show-sql: true  # SQL 문 출력 활성화
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅 활성화, 가독성 향상

springdoc:
  show-login-endpoint: true  # SpringDoc 로그인 엔드포인트 표시

logging:
  level:
    root: INFO  # 기본 로깅 레벨
    org.springframework.web: DEBUG  # Spring MVC 디버그 정보
    org.hibernate.SQL: DEBUG  # Hibernate SQL 디버그 정보
    org.hibernate.type: TRACE  # Hibernate 타입 바인딩 추적
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"  # 로그 출력 포맷

security:
  basic:
    enabled: false  # 기본 HTTP 보안 비활성화, 보안 강화 필요